###
GET http://localhost:8000/api/users

###
GET http://localhost:8000/api/users/1

###
POST http://localhost:8000/api/users
Content-Type: application/json

{
    "username": "John 111",
    "password": "john111@google.com"
}

###
PUT http://localhost:8000/api/users/2
Content-Type: application/json

{
    "username": "John 222",
    "password": "@google.com"
}

###
DELETE http://localhost:8000/api/users/2